# Generated by Django 3.1.7 on 2021-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210403_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_auth',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trader_auth',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
