# Generated by Django 3.1.7 on 2021-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210403_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader_auth',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
