# Generated by Django 3.2 on 2021-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210407_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_auth',
            name='photo',
            field=models.ImageField(upload_to='farmer/'),
        ),
        migrations.AlterField(
            model_name='trader_auth',
            name='photo',
            field=models.ImageField(upload_to='trader/'),
        ),
    ]
