# Generated by Django 3.2 on 2021-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210410_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader_auth',
            name='photo',
            field=models.ImageField(upload_to='media/trader'),
        ),
    ]
