# Generated by Django 3.2 on 2021-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_trader_auth_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_auth',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer_auth',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
