# Generated by Django 3.2 on 2021-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20210413_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_auth',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
