# Generated by Django 3.2 on 2021-04-21 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0017_auto_20210414_2130'),
        ('farmers', '0004_crops_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('crops_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crops')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer_auth')),
            ],
        ),
    ]
