# Generated by Django 3.2 on 2021-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_remove_orders_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trader_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='crops_id',
            field=models.IntegerField(null=True),
        ),
    ]
