# Generated by Django 3.1.7 on 2021-04-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210403_1159'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirm', models.BooleanField(max_length=255)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crops')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.trader_auth')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crops')),
            ],
        ),
    ]
