# Generated by Django 3.2 on 2021-04-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_trader_auth_photo'),
        ('farmers', '0002_images_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='farmer_id',
            field=models.ForeignKey(db_column='farmer_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer_auth'),
        ),
    ]
