# Generated by Django 3.2 on 2021-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_crops_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
